package com.training.algorithm.hashtable;

/**
 * Created by j-yangbo on 2017/4/26.
 * <p>
 * 389. Find the Difference
 * <p>
 * <p>
 * Given two strings s and t which consist of only lowercase letters.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Find the letter that was added in t.
 * <p>
 * Example:
 * <p>
 * Input:
 * s = "abcd"
 * t = "abcde"
 * <p>
 * Output:
 * e
 * <p>
 * Explanation:
 * 'e' is the letter that was added.
 */
public class FindtheDifference {

    public char findTheDifference(String s, String t) {
        char c =0;
        for (int i = 0; i < s.length(); i++) {
            c^=s.charAt(i);
        }
        for (int i = 0; i < t.length(); i++) {
            c^=t.charAt(i);
        }
        return c;


    }


    public static void main(String[] args) {

        FindtheDifference findtheDifference = new FindtheDifference();
        String s = "abcd";
//        String t = "abcde";
        String t = "abbcd";
        System.out.println(""+findtheDifference.findTheDifference(s,t));
    }
}
